linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocritic
    - revive
    - ineffassign
    - unused
    - gosec
    - misspell
    - testifylint
    - gosimple
    - bodyclose
    - noctx
    - whitespace

linters-settings:
  testifylint:
    enable-all: true
  revive:
    rules:
      - name: exported
      - name: if-return
      - name: var-naming
      - name: package-comments

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
